name: PHP CodeSniffer

on:
  push:
    branches:
      - '**'

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Get changed PHP files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' > changed-files.txt || echo "" > changed-files.txt

      - name: Debug Changed Files
        run: |
          echo "Changed files:"
          cat changed-files.txt || echo "No changed files detected."

      - name: Run PHP CodeSniffer
        run: |
          if [ -s changed-files.txt ]; then
            xargs -a changed-files.txt ./vendor/bin/phpcs --standard=PSR12
          else
            echo "No PHP files changed. Skipping PHP CodeSniffer."
          fi
